/**
 * Repository-specific configuration for Knip dependency analysis.
 *
 * @packageDocumentation
 */
import type { KnipConfig } from "knip";

/**
 * Knip configuration that scopes entry points and dependency heuristics to the
 * Uptime Watcher monorepo layout.
 */
const knipConfig: KnipConfig = {
    $schema: "https://unpkg.com/knip@5/schema.json",
    entry: [],
    ignore: [
        "**/*.bench.ts",
        "**/*.spec.ts",
        "**/*.test.ts",
        "**/test/**",
        "**/tests/**",
        "benchmarks/**",
        "docs/**",
        "docs/docusaurus/src/css/custom.css",
        "config/linting/plugins/uptime-watcher/_internal/repo-paths.mjs",
        "docs/docusaurus/src/components/HomepageFeatures/styles.module.css.d.ts",
        // User-request: ignore IPC validator files currently flagged by knip.
        "electron/services/ipc/validators/cloudValidation.ts",
        "electron/services/ipc/validators/shared.ts",
        "electron/services/ipc/validators/utils/commonValidators.ts",
        "electron/services/ipc/validators/utils/diagnosticsValidation.ts",
        "electron/services/ipc/validators/utils/guardReportValidation.ts",
        "electron/services/ipc/validators/utils/siteValidation.ts",
        "docs/docusaurus/typedoc-plugins/hashToBangLinks.mjs",
        "docs/docusaurus/typedoc-plugins/hashToBangLinksCore.mjs",
        "docs/docusaurus/typedoc-plugins/prefixDocLinks.mjs",
        "docs/docusaurus/typedoc-plugins/prefixDocLinksCore.mjs",
        "docs/docusaurus/typedoc-plugins/hashToBangLinksCore.d.mts",
        "docs/docusaurus/typedoc-plugins/prefixDocLinksCore.d.mts",
        "scripts/**",
        "shared/types/monitorTypes.ts",
        "shared/types/themeConfig.ts",
    ],
    ignoreBinaries: [
        "deploy",
        "detect-secrets",
        "docusaurus",
        "gh",
        "git-cz",
        "grype",
        "hint",
        "jq",
        "markdownlint",
        "npm-check",
        "open-cli",
        "powershell",
        "repomix",
        "resolve-audit",
        "rimraf",
        "scorecard-check",
        "serve",
        "shellcheck",
        "sloc",
        "ts-node",
        "tsg",
        "typesync",
        "winget",
        // False-positive: Knip treats the `-c config/tools/knip.config.ts`
        // CLI argument in package.json scripts as an unlisted binary.
        "config/tools/knip.config.ts",
    ],
    ignoreDependencies: [
        ".*eslint-formatter-.*",
        ".*prettier.*",
        "@commitlint.*",
        "@cspell.*",
        "@csstools/stylelint-formatter-github",
        "@dword-design/eslint-plugin-import-alias",
        "@electron/notarize",
        "@eslint.*",
        "@executeautomation/database-server",
        "@jscpd.*",
        "@microsoft/tsdoc-config",
        "@modelcontextprotocol/server-sequential-thinking",
        "@putout.*",
        "@secretlint.*",
        "@snyk/protect",
        "@storybook.*",
        "@stylelint.*",
        "@tailwindcss/forms",
        "@tailwindcss/typography",
        "@types.*",
        "@vitest.*",
        "@docusaurus/faster",
        "@docusaurus/theme-search-algolia",
        "@easyops-cn/docusaurus-search-local",
        "async",
        "chartjs-adapter-date-fns",
        "chartjs-plugin-zoom",
        "cli-table3",
        "cssnano",
        "cssnano-preset-advanced",
        "docusaurus-plugin-typedoc",
        "electron.*",
        "eslint.*",
        "estree",
        "fast-deep-equal",
        "force",
        "fs-extra",
        "globals-vitest",
        "gray-matter",
        "istanbul.*",
        "lcov-result-merger",
        "madge",
        "markdown-to-jsx",
        "markdownlint",
        "node-abi",
        "nyc",
        "pkg-types",
        "postcss.*",
        "putout",
        "react-chartjs-2",
        // False-positive: the project imports icons from deep entrypoints
        // (e.g. `react-icons/fi`). Knip does not currently attribute those
        // imports back to the top-level `react-icons` dependency.
        "react-icons",
        "react-refresh",
        "remark.*",
        "stylelint.*",
        "tailwind.*",
        "tidy-markdown",
        "ts.*",
        "tw-animate-css",
        "type.*",
        "unified",
        "vite.*",
        "ws",
        "zod-fast-check",
        // False-positive: `@vitejs/plugin-react` accepts babel plugins by name
        // (see `vite.config.ts`). Knip cannot attribute that string reference
        // to this devDependency.
        "babel-plugin-react-compiler",
    ],
    ignoreExportsUsedInFile: {
        interface: true,
        type: true,
    },
    ignoreUnresolved: ["@easyops-cn/docusaurus-theme-docusaurus-search-local"],
    includeEntryExports: true,
    project: [],
    rules: {
        binaries: "error",
        // eslint-disable-next-line unicorn/no-keyword-prefix -- Knip's "classMembers" rule is about class member dependencies, not about class members in general.
        classMembers: "warn",
        dependencies: "error",
        devDependencies: "error",
        duplicates: "error",
        enumMembers: "warn",
        exports: "warn",
        files: "error",
        nsExports: "warn",
        nsTypes: "warn",
        optionalPeerDependencies: "error",
        types: "warn",
        unlisted: "error",
        unresolved: "error",
    },
    workspaces: {
        ".": {
            entry: [],
            project: [],
        },
        src: {
            entry: ["src/plugin.ts"],
            project: [
                "!src/**/*.spec.{js,ts,tsx,jsx,mts,cjs,cts,mjs}",
                "!src/**/*.test.{js,ts,tsx,jsx,mts,cjs,cts,mjs}",
                "src/**/*.{js,ts,tsx,jsx,mts,cjs,cts,mjs}",
            ],
        },
    },
};

export default knipConfig;
