/**
 * @packageDocumentation
 * Canonical authored preset membership per rule id.
 */

import type { TypefestConfigName } from "./typefest-config-references.js";

/**
 * Registry of authored preset membership by unqualified rule id.
 */
export const rulePresetMembershipByRuleName: Readonly<
    Record<string, readonly TypefestConfigName[]>
> = {
    "prefer-ts-extras-array-at": ["all", "strict"],
    "prefer-ts-extras-array-concat": ["all", "strict"],
    "prefer-ts-extras-array-find": ["all"],
    "prefer-ts-extras-array-find-last": ["all", "strict"],
    "prefer-ts-extras-array-find-last-index": ["all"],
    "prefer-ts-extras-array-first": ["all", "strict"],
    "prefer-ts-extras-array-includes": [
        "all",
        "recommended",
        "strict",
        "ts-extras/type-guards",
    ],
    "prefer-ts-extras-array-join": ["all", "strict"],
    "prefer-ts-extras-array-last": [
        "all",
        "recommended",
        "strict",
    ],
    "prefer-ts-extras-as-writable": ["all", "strict"],
    "prefer-ts-extras-assert-defined": [
        "all",
        "recommended",
        "strict",
        "ts-extras/type-guards",
    ],
    "prefer-ts-extras-assert-error": [
        "all",
        "recommended",
        "strict",
        "ts-extras/type-guards",
    ],
    "prefer-ts-extras-assert-present": [
        "all",
        "recommended",
        "strict",
        "ts-extras/type-guards",
    ],
    "prefer-ts-extras-is-defined": [
        "all",
        "recommended",
        "strict",
        "ts-extras/type-guards",
    ],
    "prefer-ts-extras-is-defined-filter": [
        "all",
        "minimal",
        "recommended",
        "strict",
        "ts-extras/type-guards",
    ],
    "prefer-ts-extras-is-empty": [
        "all",
        "recommended",
        "strict",
        "ts-extras/type-guards",
    ],
    "prefer-ts-extras-is-equal-type": ["all"],
    "prefer-ts-extras-is-finite": [
        "all",
        "recommended",
        "strict",
        "ts-extras/type-guards",
    ],
    "prefer-ts-extras-is-infinite": [
        "all",
        "recommended",
        "strict",
        "ts-extras/type-guards",
    ],
    "prefer-ts-extras-is-integer": [
        "all",
        "recommended",
        "strict",
        "ts-extras/type-guards",
    ],
    "prefer-ts-extras-is-present": [
        "all",
        "recommended",
        "strict",
        "ts-extras/type-guards",
    ],
    "prefer-ts-extras-is-present-filter": [
        "all",
        "minimal",
        "recommended",
        "strict",
        "ts-extras/type-guards",
    ],
    "prefer-ts-extras-is-safe-integer": [
        "all",
        "recommended",
        "strict",
        "ts-extras/type-guards",
    ],
    "prefer-ts-extras-key-in": [
        "all",
        "recommended",
        "strict",
        "ts-extras/type-guards",
    ],
    "prefer-ts-extras-not": [
        "all",
        "recommended",
        "strict",
        "ts-extras/type-guards",
    ],
    "prefer-ts-extras-object-entries": ["all", "strict"],
    "prefer-ts-extras-object-from-entries": ["all", "strict"],
    "prefer-ts-extras-object-has-in": [
        "all",
        "recommended",
        "strict",
        "ts-extras/type-guards",
    ],
    "prefer-ts-extras-object-has-own": [
        "all",
        "recommended",
        "strict",
        "ts-extras/type-guards",
    ],
    "prefer-ts-extras-object-keys": ["all", "strict"],
    "prefer-ts-extras-object-values": ["all", "strict"],
    "prefer-ts-extras-safe-cast-to": [
        "all",
        "recommended",
        "strict",
        "ts-extras/type-guards",
    ],
    "prefer-ts-extras-set-has": [
        "all",
        "recommended",
        "strict",
        "ts-extras/type-guards",
    ],
    "prefer-ts-extras-string-split": ["all", "strict"],
    "prefer-type-fest-abstract-constructor": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-arrayable": [
        "all",
        "minimal",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-async-return-type": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-conditional-pick": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-constructor": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-except": [
        "all",
        "minimal",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-if": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-iterable-element": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-json-array": [
        "all",
        "minimal",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-json-object": [
        "all",
        "minimal",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-json-primitive": [
        "all",
        "minimal",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-json-value": [
        "all",
        "minimal",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-keys-of-union": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-literal-union": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-merge-exclusive": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-non-empty-tuple": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-omit-index-signature": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-partial-deep": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-primitive": [
        "all",
        "minimal",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-promisable": [
        "all",
        "minimal",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-readonly-deep": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-require-all-or-none": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-require-at-least-one": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-require-exactly-one": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-require-one-or-none": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-required-deep": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-schema": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-set-non-nullable": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-set-optional": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-set-readonly": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-set-required": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-simplify": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-tagged-brands": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-tuple-of": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-unknown-array": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-unknown-map": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-unknown-record": [
        "all",
        "minimal",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-unknown-set": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-unwrap-tagged": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-value-of": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-writable": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
    "prefer-type-fest-writable-deep": [
        "all",
        "recommended",
        "strict",
        "type-fest/types",
    ],
} as const;

export default rulePresetMembershipByRuleName;
