import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    docs: [
        "intro",
        "getting-started",
        {
            type: "category",
            label: "Developer",
            link: {
                type: "doc",
                id: "developer/index",
            },
            items: [{ type: "autogenerated", dirName: "developer/api" }],
        },
    ],
};

export default sidebars;
