import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    docs: [
        {
            className: "sb-doc-overview",
            id: "intro",
            label: "🏁 Overview",
            type: "doc",
        },
        {
            className: "sb-doc-getting-started",
            id: "getting-started",
            label: "🚀 Getting Started",
            type: "doc",
        },
        {
            className: "sb-cat-developer",
            collapsed: true,
            customProps: {
                badge: "api",
            },
            type: "category",
            label: "🧰 Developer API",
            link: {
                type: "doc",
                id: "developer/index",
            },
            items: [
                {
                    className: "sb-doc-api-overview",
                    href: "/docs/developer/api",
                    label: "📘 API Overview",
                    type: "link",
                },
                {
                    className: "sb-cat-api-types",
                    collapsed: true,
                    customProps: {
                        badge: "types",
                    },
                    items: [
                        {
                            dirName: "developer/api/type-aliases",
                            type: "autogenerated",
                        },
                    ],
                    label: "🧠 Type Aliases",
                    link: {
                        description:
                            "Type-level contracts and shared type aliases exposed by the plugin.",
                        title: "Type Aliases",
                        type: "generated-index",
                    },
                    type: "category",
                },
                {
                    className: "sb-cat-api-runtime",
                    collapsed: true,
                    customProps: {
                        badge: "runtime",
                    },
                    items: [
                        {
                            dirName: "developer/api/variables",
                            type: "autogenerated",
                        },
                    ],
                    label: "⚙️ Runtime Exports",
                    link: {
                        description:
                            "Runtime values and configuration exports from eslint-plugin-typefest.",
                        title: "Runtime Exports",
                        type: "generated-index",
                    },
                    type: "category",
                },
            ],
        },
    ],
};

export default sidebars;
